export default {
    '0': {
        topLeft: 1,
        topRight: 1,
        rightTop: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
        leftBottom: 1,
        leftTop: 1,
    },
    '1': {
        topRight: 1,
        rightTop: 1,
        rightBottom: 1,
    },
    '2': {
        topLeft: 1,
        topRight: 1,
        rightTop: 1,
        bottomRight: 1,
        bottomLeft: 1,
        leftBottom: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    '3': {
        topLeft: 1,
        topRight: 1,
        rightTop: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    '4': {
        rightTop: 1,
        rightBottom: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    '5': {
        topLeft: 1,
        topRight: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    '6': {
        topLeft: 1,
        topRight: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
        leftBottom: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    '7': {
        topLeft: 1,
        topRight: 1,
        rightTop: 1,
        rightBottom: 1,
    },
    '8': {
        topLeft: 1,
        topRight: 1,
        rightTop: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
        leftBottom: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    '9': {
        topLeft: 1,
        topRight: 1,
        rightTop: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    A: {
        topLeft: 1,
        topRight: 1,
        rightTop: 1,
        rightBottom: 1,
        leftBottom: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    B: {
        topLeft: 1,
        topRight: 1,
        bottomLeft: 1,
        bottomRight: 1,
        leftBottom: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
        rightBottom: 1,
    },
    C: {
        topRight: 1,
        topLeft: 1,
        leftTop: 1,
        leftBottom: 1,
        bottomLeft: 1,
        bottomRight: 1,
    },
    D: {
        topLeft: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
        leftBottom: 1,
        leftTop: 1,
    },
    E: {
        topLeft: 1,
        topRight: 1,
        bottomRight: 1,
        bottomLeft: 1,
        leftBottom: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    F: {
        topLeft: 1,
        topRight: 1,
        leftBottom: 1,
        leftTop: 1,
        centerLeft: 1,
    },
    G: {
        topLeft: 1,
        topRight: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
        leftBottom: 1,
        leftTop: 1,
        centerRight: 1,
    },
    H: {
        rightTop: 1,
        rightBottom: 1,
        leftBottom: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    I: {
        topLeft: 1,
        topRight: 1,
        bottomRight: 1,
        bottomLeft: 1,
        centerTop: 1,
        centerBottom: 1,
    },
    J: {
        topRight: 1,
        rightTop: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
    },
    K: {
        leftBottom: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
        rightBottom: 1,
    },
    L: {
        bottomLeft: 1,
        bottomRight: 1,
        leftBottom: 1,
        leftTop: 1,
    },
    M: {
        topLeft: 1,
        topRight: 1,
        rightTop: 1,
        rightBottom: 1,
        leftBottom: 1,
        leftTop: 1,
        centerTop: 1,
    },
    N: {
        rightTop: 1,
        rightBottom: 1,
        leftBottom: 1,
        leftTop: 1,
    },
    O: {
        topLeft: 1,
        topRight: 1,
        rightBottom: 1,
        rightTop: 1,
        bottomLeft: 1,
        bottomRight: 1,
        leftBottom: 1,
        leftTop: 1,
    },
    P: {
        topLeft: 1,
        topRight: 1,
        rightTop: 1,
        leftBottom: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    Q: {
        topLeft: 1,
        topRight: 1,
        rightTop: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
        leftBottom: 1,
        leftTop: 1,
    },
    R: {
        topLeft: 1,
        topRight: 1,
        rightTop: 1,
        leftBottom: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    S: {
        topRight: 1,
        topLeft: 1,
        leftTop: 1,
        centerLeft: 1,
        centerRight: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
    },
    T: {
        topLeft: 1,
        topRight: 1,
        centerTop: 1,
        centerBottom: 1,
    },
    U: {
        rightTop: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
        leftBottom: 1,
        leftTop: 1,
    },
    V: {},
    W: {
        rightTop: 1,
        rightBottom: 1,
        bottomRight: 1,
        bottomLeft: 1,
        leftBottom: 1,
        leftTop: 1,
        centerBottom: 1,
    },
    X: {},
    Y: {
        rightTop: 1,
        leftTop: 1,
        centerBottom: 1,
        centerLeft: 1,
        centerRight: 1,
    },
    Z: {},
    '+': {
        centerTop: 1,
        centerRight: 1,
        centerBottom: 1,
        centerLeft: 1,
    },
    '=': {
        centerLeft: 1,
        centerRight: 1,
        bottomLeft: 1,
        bottomRight: 1,
    },
    '-': {
        centerLeft: 1,
        centerRight: 1,
    },
    _: {
        bottomLeft: 1,
        bottomRight: 1,
    },
    '?': {
        leftTop: 1,
        topLeft: 1,
        topRight: 1,
        rightTop: 1,
        centerRight: 1,
        centerBottom: 1,
    },
    '!': {
        centerTop: 1,
        centerBottom: 1,
    },
    '[': {
        topRight: 1,
        centerTop: 1,
        centerBottom: 1,
        bottomRight: 1,
    },
    ']': {
        topLeft: 1,
        centerTop: 1,
        centerBottom: 1,
        bottomLeft: 1,
    },
    ' ': {},
}
